BLOCKS={
"OPEN":"In Phase 1, we laid out the record. From 1907 to 1912, the State of California and the federal government required every rancher in quarantined Orange County to dip cattle in arsenic, on the land that became Ladera Ranch. Since that video was posted, Ladera Ranch and ProtectLadera have been doing what they can to keep this community safe going forward. That work matters. This video is about something more immediate.",
"THREAT":"In August 2026, in the open space above the community, we found a concrete rectangle with iron pipe rails still leading up to it. Its floor is twelve feet long. The floor of a federal-specification dipping vat is twelve feet long. It is unfenced, unmarked, on public open space, beside a trail. The federal cadence for a herd this size required three to seven of these stations. One has been found. The rest have never been looked for. That is the immediate question: what is in the ground at this site and the others, and who is walking across it.",
"FL":"Florida ran the same federal program, and Florida kept records. The state inventoried more than three thousand of these vats. When it tested twelve of them, eleven failed the soil standard for arsenic. Its own report notes the abandoned vats were reused as pesticide mixing pits and as swimming holes for children. Florida found them, fenced them, and cleaned them up. California never inventoried a single one.",
"1":"Here is what a station looked like, rebuilt to the federal drawings. Pens to hold the herd. A chute to the vat. Twenty-six feet long at the rim, six and a half feet deep, holding roughly two thousand gallons. The instructions came printed in a federal circular: eight pounds of arsenic trioxide for every five hundred gallons of water, poured in by hand. Every animal driven through, head under, and out the other side. Every fourteen days, for five years. Then a dripping pen, where the dip ran off the cattle and back into the ground. When the timber rotted away, only the concrete survived. The outline we found matches the floor of this vat.",
"1b":"One station could not dip a herd this size. The federal cadence required three to seven vats, spread across the ranch's water points. Only one has been found.",
"2":"The record is not a rumor. The federal circular names Orange County as heavily infested, and reports a single ranch of about twenty-one thousand head still under quarantine in 1910. The family's own history puts the herd at more than twenty-five thousand. Run the arithmetic. Twenty-five thousand cattle, dipped every two weeks, for five years, in a dip that was one part arsenic to every sixty parts water. Between six thousand seven hundred and thirty-nine thousand pounds of arsenic went into that dip. Arsenic is an element. It does not break down. It does not go away. Whatever was introduced in 1907 is still somewhere on this landscape. If a vat stood where this concrete is, one to eight thousand pounds of it would be concentrated in the vat, the pens, and the corrals: hundreds of times the natural background of California soil, in an area the size of a few house lots. To put that mass in perspective: a lethal dose of arsenic is measured in a fraction of a gram.",
"3":"Then, between 1997 and 2007, the ground was graded. At the peak of construction, in 2002, more than four in ten acres of the community were bare, moving earth. Whatever sat in that soil was cut, filled, hauled, and spread, with no one testing for it. Because no one knew to look.",
"4":"Soil-bound material moves three ways. Earthmoving relocates it. Wind lifts it off bare, graded ground and carries it downwind, onto the first homes, the first yards, the first schools. And water. Rain and irrigation wash the finest particles down the drainage, where they settle wherever the flow slows, and where today's runoff is captured and sprayed back across the community's slopes and parks. None of this has been measured. That is the point.",
"TS":"On the walk down to the vat, there is a tire swing. This is a place where children play. This ground should be tested and secured by the State of California, independently of Ladera Ranch and of Rancho Mission Viejo.",
"PD":"Below the vat site, at the edge of the golf course, there is a pond. The federal survey mapped standing water here in 1968: a stock-water point, where cattle would have gathered. Follow the same ground back through the aerial record. 2025. 2004. 1969. 1947. 1937. 1929. This corridor was never graded. Whatever washed down this slope for a century settled here. Look at the dead vegetation around it, and the fairway beside it. Its sediment has never been sampled.",
"TR":"A public hiking and biking trail runs directly past the old fence line and the concrete. Families use it every weekend. Until this ground is tested, the State should close it, mark it, and sample it under hazardous-materials protocol.",
"5":"The drinking water has been checked. It is imported, it is tested, and it is clean. The soil has not. Not by the developer, not by the county, not by the state. Not once, in twenty years. We have mapped where a vat would have stood, where the cattle gathered, and where the drainage settles. Twenty-three ranked targets. A negative result would be a real result. But there is only one way to get any result at all. Test the soil.",
"P3":"One more thing, and it is the hardest part to say carefully. The homes here were built between 1999 and 2006, and grading peaked in 2002. Families moved in while the earth was still moving. Some of those families were expecting. Ewing sarcoma is a cancer of childhood and adolescence, and the science on it has changed. A model published in 2025 proposes a two-step disease: an initiating event before birth, and emergence years later, in puberty. Separately, studies in Chile have shown that arsenic exposure in the womb can cause cancers that surface decades later. Those are two separate findings. No study has ever connected them to each other, or to this community. I am not an oncologist. But if my child were diagnosed with one of these rare cancers, and I knew this history, I would want to know whether my wife was here, on this ground, during her pregnancy. That is not mine to decide. It could be a Phase 3 study, with real medical data and real statistics. It is not our focus now. Our focus is the ground.",
"6":"This is an independent research project. It does not establish that anything caused any illness. It asks one question that no agency has ever asked here. California: test the soil."}
ORDER=["OPEN","THREAT","FL","1","1b","2","3","4","TS","PD","TR","5","P3","6"]
